#!/usr/bin/env python3
"""Turn a TTF into an Adafruit_GFX font header, without freetype's C toolchain.

The device and the phone are meant to read as one product, and they cannot
while the panel has only FreeMono — a typewriter face — and the app sets its
headlines in IBM Plex Serif. This puts the app's ACTUAL face on the panel, so
`Jota` is the same shape in the hand and on the screen.

Adafruit's own fontconvert needs libfreetype-dev; Pillow already rasterises
TrueType, and the GFXfont layout is small enough to emit directly:

    GFXglyph { uint16 bitmapOffset; uint8 width, height, xAdvance;
               int8 xOffset, yOffset; }
    GFXfont  { uint8_t *bitmap; GFXglyph *glyph; uint16 first, last;
               uint8 yAdvance; }

Glyph bitmaps are a CONTINUOUS bitstream, MSB first, w*h bits per glyph with no
per-row padding — that packing is the only fiddly part.

    python3 ttf_to_gfx.py FONT.ttf 26 JotaSerif26 > out.h
"""
import sys
from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 0x20, 0x7E


def main() -> None:
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    path, size, name = sys.argv[1], int(sys.argv[2]), sys.argv[3]
    font = ImageFont.truetype(path, size)
    ascent, descent = font.getmetrics()

    bitmap: list[int] = []
    glyphs: list[tuple] = []

    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        # Render on a generous canvas, then crop to the ink. Cropping is what
        # keeps the bitmap small; the offsets carry the position instead.
        pad = size
        img = Image.new("1", (size * 3 + pad * 2, size * 3 + pad * 2), 0)
        d = ImageDraw.Draw(img)
        d.text((pad, pad), ch, font=font, fill=1)
        box = img.getbbox()

        adv = int(round(font.getlength(ch)))
        if box is None:                     # space and friends: no ink at all
            glyphs.append((len(bitmap), 0, 0, adv, 0, 0))
            continue

        x0, y0, x1, y1 = box
        w, h = x1 - x0, y1 - y0
        crop = img.crop(box)
        px = crop.load()

        off = len(bitmap)
        bits, acc, n = [], 0, 0
        for y in range(h):
            for x in range(w):
                acc = (acc << 1) | (1 if px[x, y] else 0)
                n += 1
                if n == 8:
                    bits.append(acc); acc, n = 0, 0
        if n:                                # pad the final partial byte
            bits.append(acc << (8 - n))
        bitmap.extend(bits)

        # GFX places a glyph relative to the cursor ON THE BASELINE: xOffset is
        # rightward from the pen, yOffset is UPWARD to the bitmap's top edge and
        # so is normally negative.
        glyphs.append((off, w, h, adv, x0 - pad, y0 - pad - ascent))

    guard = name.upper()
    out = [f"// Generated by tools/fontgen/ttf_to_gfx.py — do not edit by hand.",
           f"// {path.split('/')[-1]} at {size}px, ASCII {FIRST:#04x}..{LAST:#04x}.",
           f"#pragma once", f"#include <Adafruit_GFX.h>", "",
           f"const uint8_t {name}Bitmaps[] PROGMEM = {{"]
    for i in range(0, len(bitmap), 12):
        out.append("  " + ", ".join(f"0x{b:02X}" for b in bitmap[i:i + 12]) + ",")
    out += ["};", "", f"const GFXglyph {name}Glyphs[] PROGMEM = {{"]
    for i, (o, w, h, a, xo, yo) in enumerate(glyphs):
        out.append(f"  {{ {o}, {w}, {h}, {a}, {xo}, {yo} }},"
                   f"   // 0x{FIRST + i:02X} '{chr(FIRST + i) if FIRST + i != 0x27 else chr(0x27)}'"
                   .replace("'\\''", "'"))
    out += ["};", "",
            f"const GFXfont {name} PROGMEM = {{",
            f"  (uint8_t *){name}Bitmaps, (GFXglyph *){name}Glyphs,",
            f"  0x{FIRST:02X}, 0x{LAST:02X}, {ascent + descent}",
            "};", ""]
    print("\n".join(out))


if __name__ == "__main__":
    main()
